name: Christian Assembly Upstate
favicon: null
layout_spectrum: 0.01745
typography_spectrum: 0.08400703920051455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a9161a'
    - '#ffffff'
    - '#187ff3'
    - '#c4934e'
  brandStrength: 0.16453567100688815
  lightness: 0.5810267785564065
  saturation: 0.125
  rhythmicContrast: 0.053550741635262966
purpose: []
