layout_spectrum: 0
favicon: null
name: Christian Assembly Upstate
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.125
  saturation: 0.125
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#836437'
    - '#d3b486'
    - '#46c595'
  lightness: 0.5
  rhythmicContrast: 0.05355074163526297
typography_spectrum: 0.2765957
