layout_spectrum: 0.2340426
favicon: null
name: Christian Assembly Upstate
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.1645356710068882
  saturation: 0.125
  brandColors:
    - '#000000'
    - '#a9161a'
    - '#ffffff'
    - '#187ff3'
    - '#c4934e'
  lightness: 0.5810267785564065
  rhythmicContrast: 0.05355074163526297
typography_spectrum: 0.08400703920051455
