typography_spectrum: 0.2770902970805764
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.06360294949263334
  lightness: 0.759592805756256
  saturation: 0.29032332566566765
  rhythmicContrast: 0.5653577758930624
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8460418859031051
analytics:
  google: null
  facebook: null
  twitter: null
name: Christian Assembly Upstate
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Connect
    id: 9d982a47-2d2a-492e-aea9-e65521b66417
    type: content
  - name: Contact Us
    id: cebcafec-6c4d-4a5d-b274-eed08a5a44bb
    type: content
  - name: Giving
    id: bd1b1b4f-98f0-4d38-89a4-17c308258fac
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
