name: Christian Assembly Upstate
favicon: null
layout_spectrum: 0.05355
typography_spectrum: 0.18231
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefff1'
    - '#fcd575'
    - '#e2983e'
    - '#843958'
    - '#c0724d'
  brandStrength: 0.6875
  lightness: 0.5810267785564065
  saturation: 0.125
  rhythmicContrast: 0.05355074163526297
purpose: []
