name: Christian Assembly Upstate
favicon: null
layout_spectrum: 0.8460418859031051
typography_spectrum: 0.2770902970805764
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.06360294949263334
  lightness: 0.759592805756256
  saturation: 0.29032332566566765
  rhythmicContrast: 0.5653577758930624
purpose: []
