name: Christian Assembly Upstate
favicon: null
layout_spectrum: 0.24451
typography_spectrum: 0.2765957
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#836437'
    - '#d3b486'
    - '#46c595'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.05355074163526297
purpose: []
